[package]
name = "day04"
version = "0.1.0"
authors = ["Ethan Mott <ethanmott@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
lazy_static = "1.4.0"
regex = "1"
